#!/bin/bash

d1=${1:-original}
d2=${2:-fallback}
s3=${3:-""}

started=n
for f in $d2/*.desktop
do
	f=$(basename $f)
	if [ "$s3" != "" -a "$started" = "n" ]
	then
		s=$(basename $f .desktop)
		if [ "$s3" = "$s" ]
		then
			started=y
		else
			echo "--> skipping $f (for $s3.desktop)"
			continue
		fi
	fi
	if [ ! -r $d1/$f ]
	then
		continue
	fi
	if diff -q $d2/$f $d1/$f
	then
		echo "--> match $f"
	else
		vimdiff $d2/$f $d1/$f
		echo -n "continue? "
		read line
		if [[ "$line" = "q" ]]
		then
			break
		fi
	fi
done

exit 0

