#!/bin/bash

d1=${1:-original}

for f in $d1/*.desktop
do
	n=$(basename $f)
	if grep -q 'X-Arch-Package-Version=' $f
	then
		echo "--> has package: $f"
		if [ ! -r fallback/$n ]
		then
			cp -v $d1/$n fallback/$n
		fi
		if [ ! -r applications/$n ]
		then
			cp -v $d1/$n applications/$n
		fi
		if [ ! -r app-install/desktop/$n ]
		then
			cp -v $d1/$n app-install/desktop/$n
		fi
	else
		echo "--> no package: $f"
	fi
done
